name: Checks

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

jobs:
  typecheck-and-format:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install

      - name: Type check (svelte-check)
        run: bun run check

      - name: Prettier check
        run: bun run lint
